num_features: 1
num_heads: 4
num_out_heads: 1
num_layers: 2
num_dec_layers: 1
num_remasking: 3
num_hidden: 64
residual: false
in_drop: 0.2
attn_drop: 0.1
norm: ~
lr: 0.0001
weight_decay: 0
negative_slope: 0.2
activation: prelu
mask_rate: 0.5
remask_rate: 0.5
remask_method: random
mask_type: mask
mask_method: random
drop_edge_rate: 0.0
drop_edge_rate_f: 0.0
encoder: gat
decoder: gat
loss_fn: sce
alpha_l: 2
optimizer: adam
scheduler: true
sampling_method: saint
label_rate: 1.0
lam: 1.0
full_graph_forward: false
delayed_ema_epoch: 0
replace_rate: 0.0
momentum: 0.996
do_feat_encoder: false
nonzero_mask: true
